"""
Compile Task into all targets.

This is the ONLY place that knows about HTTP and CLI.
Task is target-agnostic — it just declares meaning.

emergent's compiler reads @derive annotations and produces:
  - FastAPI app with 5 routes
  - CLI parser with matching commands
  - OpenAPI spec (auto-generated by FastAPI)

To add Telegram: import TG compiler here, compile(app).
Don't touch Task.
"""

from __future__ import annotations

from derivelib import build_application_from_decorated
from emergent.wire.compile.targets import fastapi, cli

from tasks.domain import Task  # noqa: F401 — triggers @derive registration

# Build the intermediate representation
app = build_application_from_decorated()

# Compile to targets
fastapi_app = fastapi.compile(app)
cli_parser = cli.compile(app, prog="tasks")
